version: '3.8'

services:
  sync-service:
    build: .
    container_name: feishu_db_sync
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config.json:/app/config.json
      - ./logs:/app/logs
    depends_on:
      - redis
      - mysql
    restart: unless-stopped
    networks:
      - sync-network

  redis:
    image: redis:7-alpine
    container_name: sync_redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - sync-network

  mysql:
    image: mysql:8.0
    container_name: sync_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: feishu_sync
      MYSQL_USER: sync_user
      MYSQL_PASSWORD: sync_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database_triggers.sql:/docker-entrypoint-initdb.d/01-triggers.sql
    networks:
      - sync-network

  # 可选：监控面板
  prometheus:
    image: prom/prometheus:latest
    container_name: sync_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    networks:
      - sync-network

  grafana:
    image: grafana/grafana:latest
    container_name: sync_grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - sync-network

networks:
  sync-network:
    driver: bridge

volumes:
  redis-data:
  mysql-data:
  prometheus-data:
  grafana-data: